name: Build and Deploy Static Site with Podman

on:
  push:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code
      uses: actions/checkout@v3

    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v2
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - name: Login to Amazon ECR using Podman
      run: |
        aws ecr get-login-password --region us-east-1 | podman login --username AWS --password-stdin 025066240744.dkr.ecr.us-east-1.amazonaws.com

    - name: Build and Push Podman Image to ECR
      env:
        IMAGE_URI: 025066240744.dkr.ecr.us-east-1.amazonaws.com/podman-static-repo:latest
      run: |
        podman build -t $IMAGE_URI .
        podman push $IMAGE_URI

    - name: Copy deploy.sh to EC2
      uses: appleboy/scp-action@v0.1.4
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "deploy.sh"
        target: "~/"

    - name: Run deploy.sh on EC2
      uses: appleboy/ssh-action@v1.0.0
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        script: |
          chmod +x ~/deploy.sh
          export AWS_ACCESS_KEY_ID=${{ secrets.AWS_ACCESS_KEY_ID }}
          export AWS_SECRET_ACCESS_KEY=${{ secrets.AWS_SECRET_ACCESS_KEY }}
          bash ~/deploy.sh
